// Define the types for Course and Video
type Video = {
    id: number;
    title: string;
    videoUrl: string;
};

type Course = {
    id: number;
    title: string;
    description: string;
    image: string;
    videos: Video[]; // Ensure videos is always present as an array
};

const courseData: Course[] = [
    {
        id: 1,
        title: "Docker Essentials",
        description: "Learn the basics of Docker and how to create and manage containers.",
        image: "/docker.jpg",
        videos: [
            { id: 1, title: "Introduction to Docker", videoUrl: "https://www.youtube.com/embed/e1hcBigmRmc" },
            { id: 2, title: "Docker Installation", videoUrl: "https://www.youtube.com/embed/zOGUydFHR1w" },
            { id: 3, title: "Docker Commands", videoUrl: "https://www.youtube.com/embed/E9KK_GmvCkw" },
            { id: 4, title: "Creating Docker Images", videoUrl: "https://www.youtube.com/embed/dheF0uqBx1k" },
            { id: 5, title: "Docker Networking", videoUrl: "https://www.youtube.com/embed/AZnfj4JALUw" },
            { id: 6, title: "Docker Compose", videoUrl: "https://www.youtube.com/embed/-hgQ-xfLch4" },
            { id: 7, title: "Docker Volumes", videoUrl: "https://www.youtube.com/embed/DmpgqHsI3vI" },
            { id: 8, title: "Docker Swarm", videoUrl: "https://www.youtube.com/embed/3ZQ2v6M1J-4" },
            { id: 9, title: "Docker Best Practices", videoUrl: "https://www.youtube.com/embed/cV4qSVDFaqI" },
            { id: 10, title: "Docker Security", videoUrl: "https://www.youtube.com/embed/N8dIGDSd0VE" },
            { id: 11, title: "Docker CI/CD", videoUrl: "https://www.youtube.com/embed/BKzy9Ww5aAg" },
            { id: 12, title: "Deploying Docker Containers", videoUrl: "https://www.youtube.com/embed/CfGP415W_RY" },
            { id: 13, title: "Troubleshooting Docker", videoUrl: "https://www.youtube.com/embed/I4emNd-0MkU" },
        ],
    },
    {
        id: 2,
        title: "Kubernetes Fundamentals",
        description: "Master the concepts of Kubernetes and orchestration of containerized applications.",
        image: "/k8s.jpg",
        videos: [
            { id: 1, title: "Kubernetes: What is it?", videoUrl: "https://www.youtube.com/embed/-suYI4pFNQo" },
            { id: 2, title: "Getting Started with Kubernetes", videoUrl: "https://www.youtube.com/embed/VFTmKbsPWws" },
            { id: 3, title: "Kubernetes Architecture", videoUrl: "https://www.youtube.com/embed/FGlv0xttkVc" },
            { id: 4, title: "Deploying Applications", videoUrl: "https://www.youtube.com/embed/rwO5s26rblc" },
            { id: 5, title: "Kubernetes Services", videoUrl: "https://www.youtube.com/embed/6hqNWWnhZjg" },
            { id: 6, title: "Managing Kubernetes Resources", videoUrl: "https://www.youtube.com/embed/G3OV4RPIcX4" },
            { id: 7, title: "Kubernetes Networking", videoUrl: "https://www.youtube.com/embed/YemrH3v1e3E" },
            { id: 8, title: "Monitoring and Logging", videoUrl: "https://www.youtube.com/embed/uUIobDBLw6o" },
            { id: 9, title: "Kubernetes Security", videoUrl: "https://www.youtube.com/embed/9JMcGr6rbO8" },
            { id: 10, title: "Kubernetes Best Practices", videoUrl: "https://www.youtube.com/embed/mGQ29xYeCrM" },
            { id: 11, title: "Troubleshooting Kubernetes", videoUrl: "https://www.youtube.com/embed/veiVV4FeB1U" },
            { id: 12, title: "Kubernetes with CI/CD", videoUrl: "https://www.youtube.com/embed/IxBGIpXLsYM" },
            { id: 13, title: "Advanced Kubernetes Features", videoUrl: "https://www.youtube.com/embed/V61fs7RhJOg" },
            { id: 14, title: "Kubernetes and Docker", videoUrl: "https://www.youtube.com/embed/3ygIh99RSwg" },
            { id: 15, title: "Scaling Applications in Kubernetes", videoUrl: "https://www.youtube.com/embed/OMzVbeTKN-o" },
            { id: 16, title: "Kubernetes Resource Management", videoUrl: "https://www.youtube.com/embed/A4svk80wPbA" },
            { id: 17, title: "Kubernetes in Production", videoUrl: "https://www.youtube.com/embed/rXTpVGIENAQ" },
            { id: 18, title: "Kubernetes Custom Resources", videoUrl: "https://www.youtube.com/embed/mkksJZZmpgE" },
            { id: 19, title: "Kubernetes Upgrades", videoUrl: "https://www.youtube.com/embed/zND4_2ZzX8g" },
            { id: 20, title: "Kubernetes Resource Quotas", videoUrl: "https://www.youtube.com/embed/K0L4AK0GN-0" },
            { id: 21, title: "Kubernetes Troubleshooting Techniques", videoUrl: "https://www.youtube.com/embed/HqFhyG67EEA" },
        ],
    },

    {
        id: 3,
        title: "Ansible for Beginners",
        description: "Learn the basics of Ansible and how to automate your IT tasks.",
        image: "/ansible.jpg",
        videos: [
            { id: 1, title: "Introduction to Ansible", videoUrl: "https://www.youtube.com/embed/XWJR6uab4nk" },
            { id: 2, title: "Ansible Installation", videoUrl: "https://www.youtube.com/embed/Fbw3TthQ-Dw" },
            { id: 3, title: "Ansible Playbooks", videoUrl: "https://www.youtube.com/embed/do6YzEMuhDM" },
            { id: 4, title: "Ansible Modules", videoUrl: "https://www.youtube.com/embed/oGjp9iHA0mI" },
            { id: 5, title: "Ansible Inventory", videoUrl: "https://www.youtube.com/embed/uwmUy08pPo4" },
            { id: 6, title: "Ansible Roles", videoUrl: "https://www.youtube.com/embed/l9KvYsxSC40" },
            { id: 7, title: "Ansible Facts", videoUrl: "https://www.youtube.com/embed/4ziFXx2dCKM" },
            { id: 8, title: "Ansible Vault", videoUrl: "https://www.youtube.com/embed/6lOc7Cxqu0w" },
            { id: 9, title: "Ansible Galaxy", videoUrl: "https://www.youtube.com/embed/u5OeXbfSGEE" },
            { id: 10, title: "Ansible Best Practices", videoUrl: "https://www.youtube.com/embed/ScFdvSXw-9s" },
            { id: 11, title: "Ansible Debugging", videoUrl: "https://www.youtube.com/embed/8eEwR1kTd9k" },
            { id: 12, title: "Ansible Ad-hoc Commands", videoUrl: "https://www.youtube.com/embed/PfzZ19sTXu8" },
            { id: 13, title: "Ansible with CI/CD", videoUrl: "https://www.youtube.com/embed/P8As5ibsNmE" },
            { id: 14, title: "Ansible in Production", videoUrl: "https://www.youtube.com/embed/minQn0WCENg" },
            { id: 15, title: "Ansible and Cloud", videoUrl: "https://www.youtube.com/embed/-eSc1KHDgxI" },
            { id: 16, title: "Ansible Troubleshooting", videoUrl: "https://www.youtube.com/embed/u5FueJ744Lk" },
            { id: 17, title: "Ansible Playbook Variables", videoUrl: "https://www.youtube.com/embed/dNzgXRUKFx4" },
        ],
    },
    {
        id: 4,
        title: "Jenkins Essentials",
        description: "Get to know Jenkins and how to implement continuous integration and delivery.",
        image: "/jenkins.png",
        videos: [
            { id: 1, title: "Introduction to Jenkins", videoUrl: "https://www.youtube.com/embed/yv04M45sPZU" },
            { id: 2, title: "Jenkins Setup", videoUrl: "https://www.youtube.com/embed/EzxDS_xmxo0" },
            { id: 3, title: "Creating Jenkins Jobs", videoUrl: "https://www.youtube.com/embed/WB6PHa7C7ec" },
            { id: 4, title: "Jenkins Pipelines", videoUrl: "https://www.youtube.com/embed/qq7_og2_S5U" },
            { id: 5, title: "Jenkins Plugins", videoUrl: "https://www.youtube.com/embed/cmpJH8XGc8Q" },
            { id: 6, title: "Jenkins with Docker", videoUrl: "https://www.youtube.com/embed/2HbohqSoqhw" },
            { id: 7, title: "Jenkins Security", videoUrl: "https://www.youtube.com/embed/6NfcMG9xAFw" },
            { id: 8, title: "Jenkins Monitoring", videoUrl: "https://www.youtube.com/embed/3b517n-pZQQ" },
            { id: 9, title: "Jenkins CI/CD", videoUrl: "https://www.youtube.com/embed/BB1dyneMD5U" },
            { id: 10, title: "Jenkins Best Practices", videoUrl: "https://www.youtube.com/embed/Q666hwsoSoY" },
            { id: 11, title: "Jenkins Troubleshooting", videoUrl: "https://www.youtube.com/embed/iklQHpUzpQY" },
            { id: 12, title: "Jenkins with Git", videoUrl: "https://www.youtube.com/embed/bQtwvkOQjiM" },
            { id: 13, title: "Advanced Jenkins Features", videoUrl: "https://www.youtube.com/embed/8pPT1qI2dMM" },
        ],
    },

    {
        id: 5,
        title: "Terraform Fundamentals",
        description: "Learn how to manage infrastructure as code using Terraform.",
        image: "/terraform.png",
        videos: [
            { id: 1, title: "Introduction to Terraform", videoUrl: "https://www.youtube.com/embed/bZKTAY-Gee4" },
            { id: 2, title: "Terraform Installation", videoUrl: "https://www.youtube.com/embed/mtByNeHM8uY" },
            { id: 3, title: "Understanding Terraform Configuration", videoUrl: "https://www.youtube.com/embed/CbYb6Cqvaz4" },
            { id: 4, title: "Terraform Providers", videoUrl: "https://www.youtube.com/embed/ZFND2v8sV9g" },
            { id: 5, title: "Managing State in Terraform", videoUrl: "https://www.youtube.com/embed/oHfy-wQCbpc" },
            { id: 6, title: "Terraform Modules", videoUrl: "https://www.youtube.com/embed/wWNI0WXK30A" },
            { id: 7, title: "Terraform Workspaces", videoUrl: "https://www.youtube.com/embed/OB_zldTq6cY" },
            { id: 8, title: "Terraform Output Values", videoUrl: "https://www.youtube.com/embed/9N0XasZdQLM" },
            { id: 9, title: "Terraform Best Practices", videoUrl: "https://www.youtube.com/embed/53lcRkWaQ0w" },
            { id: 10, title: "Terraform with CI/CD", videoUrl: "https://www.youtube.com/embed/osccdXk4NX0" },
            { id: 11, title: "Troubleshooting Terraform", videoUrl: "https://www.youtube.com/embed/fP3bFTCT5HE" },
        ],
    },
    
    {
        id: 6,
        title: "Shell Scripting Fundamentals",
        description: "Learn the basics of shell scripting to automate tasks in Unix/Linux environments.",
        image: "/shell_scripting.png",
        videos: [
            { id: 1, title: "Introduction to Shell Scripting", videoUrl: "https://www.youtube.com/embed/p0JafZBFQvs" },
            { id: 2, title: "Basic Shell Commands", videoUrl: "https://www.youtube.com/embed/N4X50gxofn4" },
            { id: 3, title: "Variables in Shell Scripts", videoUrl: "https://www.youtube.com/embed/EzTBESLcdY8" },
            { id: 4, title: "Control Structures", videoUrl: "https://www.youtube.com/embed/ZHompR7Rg0g" },
            { id: 5, title: "Functions in Shell Scripts", videoUrl: "https://www.youtube.com/embed/GDKeBnx-QAU" },
            { id: 6, title: "Working with Files", videoUrl: "https://www.youtube.com/embed/YePQOeE769Y" },
            { id: 7, title: "Error Handling in Shell Scripts", videoUrl: "https://www.youtube.com/embed/eEvvoAig4Fs" },
            { id: 8, title: "Using Loops", videoUrl: "https://www.youtube.com/embed/IoTQxELI9HQ" },
            { id: 9, title: "Regular Expressions", videoUrl: "https://www.youtube.com/embed/ZoKSd3PJ0rI" },
            { id: 10, title: "Debugging Shell Scripts", videoUrl: "https://www.youtube.com/embed/xgCHQB1PVK4" },
            { id: 11, title: "Advanced Shell Scripting Techniques", videoUrl: "https://www.youtube.com/embed/NSMV0bjHZO8" },
            { id: 12, title: "Scripting with AWK", videoUrl: "https://www.youtube.com/embed/iTAuLguJ-e8" },
            { id: 13, title: "Scripting with Sed", videoUrl: "https://www.youtube.com/embed/Ag14yVV8mmI" },
            { id: 14, title: "Using Shell Scripts in Automation", videoUrl: "https://www.youtube.com/embed/QOyjS2aZ2Rw" },
            { id: 15, title: "Best Practices for Shell Scripting", videoUrl: "https://www.youtube.com/embed/quICRSKLwiA" },
            { id: 16, title: "Shell Scripting Tips and Tricks", videoUrl: "https://www.youtube.com/embed/AJB2dJXRV7E" },
        ],
    },
    {
        id: 7,
        title: "Introduction to DevOps Culture",
        description: "Understand the principles of DevOps and how to foster a collaborative culture.",
        image: "/Devops.png",
        videos: [
            { id: 1, title: "What is DevOps?", videoUrl: "https://www.youtube.com/embed/6UX03Miffks" },
            { id: 2, title: "The DevOps Mindset", videoUrl: "https://www.youtube.com/embed/D-fZG2Lholc" },
            { id: 3, title: "Collaboration in DevOps", videoUrl: "https://www.youtube.com/embed/U1DUNaSrMng" },
            { id: 4, title: "DevOps Practices for Success", videoUrl: "https://www.youtube.com/embed/7K8wNVzttmI" },
            { id: 5, title: "Building a DevOps Culture", videoUrl: "https://www.youtube.com/embed/WvVkt9MC_rY" },
        ],
    },
    
    {
        id: 8,
        title: "AWS Cloud Practitioner",
        description: "Get started with AWS and understand cloud concepts, services, and solutions.",
        image: "/aws.jpg",
        videos: [
            { id: 1, title: "Introduction to AWS", videoUrl: "https://www.youtube.com/embed/025tGWe1zXs" },
            { id: 2, title: "AWS Core Services Overview", videoUrl: "https://www.youtube.com/embed/6VlOTMQJHy0" },
            { id: 3, title: "Understanding Cloud Concepts", videoUrl: "https://www.youtube.com/embed/LZdYiseonpE" },
            { id: 4, title: "AWS Pricing and Billing", videoUrl: "https://www.youtube.com/embed/zWiSdWA_7to" },
            { id: 5, title: "AWS Security Fundamentals", videoUrl: "https://www.youtube.com/embed/kVqQlFo7kzE" },
            { id: 6, title: "Getting Started with AWS Management Console", videoUrl: "https://www.youtube.com/embed/kWgQNw-L1P4" },
            { id: 7, title: "AWS Global Infrastructure", videoUrl: "https://www.youtube.com/embed/KuQIbIjlXkc" },
            { id: 8, title: "AWS Storage Options", videoUrl: "https://www.youtube.com/embed/isBFtg6Vns4" },
            { id: 9, title: "Deploying Applications on AWS", videoUrl: "https://www.youtube.com/embed/_Z3aOqRi-5M" },
            { id: 10, title: "AWS Compute Services", videoUrl: "https://www.youtube.com/embed/1J-RVqw-FVI" },
            { id: 11, title: "AWS Networking Basics", videoUrl: "https://www.youtube.com/embed/mFL89hzPc2M" },
            { id: 12, title: "AWS Databases Overview", videoUrl: "https://www.youtube.com/embed/ZIEAGjFCZ90" },
            { id: 13, title: "AWS DevOps Services", videoUrl: "https://www.youtube.com/embed/4uGraIKw25w" },
            { id: 14, title: "Monitoring AWS Resources", videoUrl: "https://www.youtube.com/embed/MB-JERFDQa8" },
            { id: 15, title: "Getting Certified as AWS Cloud Practitioner", videoUrl: "https://www.youtube.com/embed/8ieso8VEKGo" },
            { id: 16, title: "AWS Support Plans", videoUrl: "https://www.youtube.com/embed/Z2dV0aHgdaE" },
            { id: 17, title: "Best Practices for AWS", videoUrl: "https://www.youtube.com/embed/VowVAusyNvw" },
            { id: 18, title: "Navigating AWS Documentation", videoUrl: "https://www.youtube.com/embed/lQHhT2PkMZo" },
            { id: 19, title: "AWS Community and Resources", videoUrl: "https://www.youtube.com/embed/fhilLJNS0lo" },
        ],
    },
    
    {
        id: 9,
        title: "Git and GitHub for Beginners",
        description: "Learn version control with Git and how to use GitHub for collaboration.",
        image: "/git.png",
        videos: [
            { id: 1, title: "Introduction to Git", videoUrl: "https://www.youtube.com/embed/YzGn8RUNDxM" },
            { id: 2, title: "Setting Up Git and GitHub", videoUrl: "https://www.youtube.com/embed/7LJ5KdFq4Ro" },
            { id: 3, title: "Basic Git Commands", videoUrl: "https://www.youtube.com/embed/NVNTc9HAVoo" },
            { id: 4, title: "Creating a Repository", videoUrl: "https://www.youtube.com/embed/Yt6D0kh4J2w" },
            { id: 5, title: "Committing Changes in Git", videoUrl: "https://www.youtube.com/embed/Dp6MM97IYX4" },
            { id: 6, title: "Collaborating on GitHub", videoUrl: "https://www.youtube.com/embed/WoB903Zl_jo" },
        ],
    },
    {
        id: 10,
        title: "Site Reliability Engineering (SRE)",
        description: "Explore the principles and practices of Site Reliability Engineering.",
        image: "/sre.png",
        videos: [
            { id: 1, title: "Introduction to SRE", videoUrl: "https://www.youtube.com/embed/U1Fv8B-seF0" },
            { id: 2, title: "SRE Practices", videoUrl: "https://www.youtube.com/embed/vknoGWMyx24" },
            { id: 3, title: "Understanding Service Level Objectives (SLOs)", videoUrl: "https://www.youtube.com/embed/Arj1nCtzY1U" },
            { id: 4, title: "Incident Management in SRE", videoUrl: "https://www.youtube.com/embed/E5Oy-Tj3LN4" },
            { id: 5, title: "Monitoring and Observability", videoUrl: "https://www.youtube.com/embed/Pa5nCJRY6ds" },
            { id: 6, title: "SRE and DevOps", videoUrl: "https://www.youtube.com/embed/OHWps7DTGis" },
            { id: 7, title: "Managing SRE Teams", videoUrl: "https://www.youtube.com/embed/P11N19u6eJ4" },
            { id: 8, title: "SRE Best Practices", videoUrl: "https://www.youtube.com/embed/-TyIGl1TmnQ" },
        ],
    },    
];

export default courseData;